### ISSUE TITLE
Deleting parameters from blueprint with Aggregate Chest crashes on save

### ISSUE THREAD

**Issue by Glockshna** [raiguard/EditorExtensions#204] opened 2024-11-30 18:51 UTC
### Description

The title says it all pretty much.

Solution would be remove the parameter item from the aggregate chest. They aren't items.

### Reproduction

 Blueprint an aggregate chest, 
 uncheck the parameters in the blueprint.
 Paste the blueprint,
 the game will crash next time it attempts to save.

**Comment by raiguard** [comment] 2024-12-04 07:06
![image](https://github.com/user-attachments/assets/3d97a08d-250e-4a22-a7b5-ebb5748a1223)

I can't reproduce because I can't set parameters in the blueprint to begin with.

**Comment by raiguard** [comment] 2024-12-04 07:14
Duplicate of #185

**Closed by raiguard** 2024-12-04 07:14 UTC
Labels: pending
