### ISSUE TITLE
[Bug+Feature request] Crash when loading EE 2.4.0 with pY without belt stacking/Make outputting stacked items a setting

### ISSUE THREAD

**Issue by jigsaw3xD** [raiguard/EditorExtensions#206] opened 2024-12-04 12:13 UTC
### Description

**Bug:**
![DNtH7lmWvN](https://github.com/user-attachments/assets/382b12a2-87e9-4c7f-9a8b-c3624771b1c5)

**Feature request:** 
In sandbox it was very convenient to attach an infinity loader to a belt that you currently have in the game to test out/see if a production line can be fully satisfied with that one belt of that material. But if loaders output stacked items now it'd be impossible to tell if what you're testing will work in the game where you don't yet/won't have stacking.

**Comment by raiguard** [comment] 2024-12-05 04:06
Even though this one was first, I'm closing this one because the other one is more succinct.

Duplicate of #208.

**Closed by raiguard** 2024-12-05 04:06 UTC
