### ISSUE TITLE
Feature request: Option for older version of Infinity Loader

### ISSUE THREAD

**Issue by adamreiswig** [raiguard/EditorExtensions#107] opened 2023-03-14 15:50 UTC
Is there any chance there will be a mod option to use the old style of Inifinty Loaders? It is, or was, one of the main reasons I use Editor Extensions. Being able to copy/paste from Constant Combinators and output two separate items was instrumental to my testing. If this is gone for good I guess I'll downgrade back to 1.13.8. Many thanks!

**Comment by raiguard** [comment] 2023-03-14 21:43
Duplicate of #105 

This isn't going to happen. The old infinity loader had some problems that I could not fix, and the code was very hard to maintain. It's unfortunate that the new one can't have split filters, but this is the only way to make it work completely correctly with blueprints.

**Closed by raiguard** 2023-03-14 21:43 UTC
